basePath: /
host: terraform-provider-luis.k8s.bestcorp.net
info:
  contact:
    name: engineering-services
  description: test
  title: terraform-provider-luis
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Returns the root route
      tags:
      - root
  /endpoint1:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: gets endpoint1
      tags:
      - endpoint1
swagger: "2.0"
